version: "3.8"
services:
  catalog_db_server:
    image: "postgres:14"
    container_name: catalog_db_1
    ports:
      - "5447:5432"
    environment:
      POSTGRES_USER: catalog_db_1
      POSTGRES_PASSWORD: catalog_db_password_1
      POSTGRES_DB: catalog_service_1
    volumes:
      - ./db-data/catalog-db-server:/var/lib/postgresql/data

  order_db_server:
    image: "postgres:14"
    container_name: order_db_1
    ports:
      - "5448:5432"
    environment:
      POSTGRES_USER: order_db_1
      POSTGRES_PASSWORD: order_db_password_1
      POSTGRES_DB: order_service_1
    volumes:
      - ./db-data/order-db-server:/var/lib/postgresql/data

  user_db_server:
    image: "postgres:14"
    container_name: user_db_1
    ports:
      - "5449:5432"
    environment:
      POSTGRES_USER: user_db_1
      POSTGRES_PASSWORD: user_db_password_1
      POSTGRES_DB: user_service_1
    volumes:
      - ./db-data/user-db-server:/var/lib/postgresql/data

  like_db_server:
    image: "postgres:14"
    container_name: like_db_1
    ports:
      - "5450:5432"
    environment:
      POSTGRES_USER: like_db_1
      POSTGRES_PASSWORD: like_db_password_1
      POSTGRES_DB: like_service_1
    volumes:
      - ./db-data/like-db-server:/var/lib/postgresql/data
